# DB Version(s): 18-19
# OS Type: linux
# DB Type: oltp
# Total Memory (RAM): 16 GB
# CPUs num: 8
# Storage: SATA SSD
max_connections = 200
shared_buffers = 4GB
effective_cache_size = 12GB
maintenance_work_mem = 2GB
random_page_cost = 1.25
effective_io_concurrency = 200
work_mem = 32MB
max_wal_size = 10GB
max_parallel_workers_per_gather = 1
max_parallel_workers = 8
max_worker_processes = 8
unix_socket_directories = '/tmp' # To run under any OS user conveniently
shared_preload_libraries = 'pg_stat_statements'
wal_compression = on # zstd should be the default actually nowadays for v15+
track_io_timing = on # To get IO call duration in pg_stat_statements
synchronous_commit = off # Don't want to test disk COMMIT throughput in this test
jit = off # off in v19 by default
