# DB Version(s): 18-19
# OS Type: linux
# DB Type: oltp
# Total Memory (RAM): 192 GB
# CPUs num: 96
# Storage: NVMe SSD
cluster_name = 'pgtesting'
max_connections = 1000
huge_pages = on  # PS Needs OS side config!
shared_buffers = 38GB  # 20%
effective_cache_size = 144GB
maintenance_work_mem = 8GB
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 64MB
max_wal_size = 30GB
max_parallel_workers_per_gather = 1
max_parallel_workers = 96
max_worker_processes = 96
unix_socket_directories = '/tmp' # To run under any OS user conveniently
shared_preload_libraries = 'pg_stat_statements'
wal_compression = on # zstd should be the default actually nowadays for v15+
track_io_timing = on # To get IO call duration in pg_stat_statements
#synchronous_commit = off # Don't want to test disk COMMIT throughput in this test
jit = off # off in v19 by default
